#!/bin/bash


function  config_pipeline_externaldb() {
  echo ""
  #echo_h2 "4. JDBC Configuration for the external database"
  echo -e "${COLOR_YELLOW}JDBC Configuration for the external database:" 
  #if prompt_for_confirm "Configure external database";  CONFIGURE_EXTERNAL_DB then

  echo "${TEXT_DIM} Sample Connection strings:"
  echo "  - DB2:"
  echo "    jdbc:db2://dbserverxx:50000/maxdbxx"
  echo "    SSL enabled:"
  echo "    jdbc:db2://dbserverxx:50000/maxdbxx:sslConnection=true"
  echo "  - Oracle:"
  echo "    jdbc:oracle:thin:@dbserverxx:1521:maximo"
  echo "  - SQL Server:"
  echo "    'jdbc:sqlserver://;serverName=dbserverxx;portNumber=1433;databaseName=msdbxx;integratedSecurity=false;sendStringParametersAsUnicode=false;selectMethod=cursor;encrypt=false;trustServerCertificate=false;'"
  echo "    SSL enabled:"
  echo "    'jdbc:sqlserver://;serverName=dbserverxx;portNumber=1433;databaseName=msdbxx;integratedSecurity=false;sendStringParametersAsUnicode=false;selectMethod=cursor;encrypt=true;trustServerCertificate=true;'"
  echo ""
  reset_colors

  # echo -e "${COLOR_YELLOW}JDBC Configuration for the external database"  
  prompt_for_input "Database Instance ID" DB_INSTANCE_ID
  prompt_for_input "Connection string" MAS_JDBC_URL
  prompt_for_input "User name" MAS_JDBC_USER
  prompt_for_input "Password" MAS_JDBC_PASSWORD
   
  prompt_for_input "Schema" MAS_APP_SETTINGS_DB2_SCHEMA
  prompt_for_input "Table space" MAS_APP_SETTINGS_TABLESPACE
  prompt_for_input "Index space" MAS_APP_SETTINGS_INDEXSPACE
  prompt_for_confirm_default_yes "SSL enabled" SSL_ENABLED

  if [[ "$SSL_ENABLED" == "true" ]]; then
    export SS=true
    prompt_for_input "Location for SSL certificate" MAS_JDBC_CERT_LOCAL_FILE
    if [[ ! -e "$MAS_JDBC_CERT_LOCAL_FILE" ]]; then
      echo_warning "Error: File does not exist: $MAS_JDBC_CERT_LOCAL_FILE"
      exit 1
    fi
  fi

  MAS_CONFIG_SCOPE="wsapp"
}

