#!/bin/bash

function  config_pipeline_externaldb() {
  echo ""
  prompt_for_confirm_default_no "+ Configure external database" CONFIGURE_EXTERNAL_DATABASE

  echo "External DB" $CONFIGURE_EXTERNAL_DATABASE

  if [[ "$CONFIGURE_EXTERNAL_DATABASE" == "true" ]]; then
    echo -e "${COLOR_YELLOW}JDBC Configuration for the external database"
    prompt_for_input "Database Instance ID" DB_INSTANCE_ID
    prompt_for_input "User" MAS_JDBC_USER
    prompt_for_input "Password" MAS_JDBC_PASSWORD
    prompt_for_input "URL" MAS_JDBC_URL
    prompt_for_input "Schema" MAS_APP_SETTINGS_DB2_SCHEMA
    prompt_for_input "Tablespace" MAS_APP_SETTINGS_TABLESPACE
    prompt_for_input "Indexspace" MAS_APP_SETTINGS_INDEXSPACE
    prompt_for_confirm_default_no "SSL" SSL_ENABLED

    if [[ "$SSL_ENABLED" == "true" ]]; then
      prompt_for_input "Location for SSL certificate" MAS_JDBC_CERT_LOCAL_FILE
      if [[ ! -e "$MAS_JDBC_CERT_LOCAL_FILE" ]]; then
        echo_warning "Error: File does not exist: $MAS_JDBC_CERT_LOCAL_FILE"
        exit 1
      fi
    fi
  
  fi
}